import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";

const firaSans = Fira_Sans({
  weight: ["500", "800"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GanttFlow",
  description: "Generated by GanttFlow",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${firaSans.className} antialiased bg-white dark:bg-gray-900 flex flex-col min-h-screen`}
      >
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
